name: api_client
description: Dart package which manages the connection to the backend.
version: 0.0.1
author: null

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0
  dio: ^3.0.10
  equatable: ^2.0.0
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  google_sign_in: ^4.5.9
  meta: ^1.2.4
  very_good_analysis: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
