include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_dynamic_calls: false
    prefer_asserts_with_message: false
    no_default_cases: false
    always_use_package_imports: false
    require_trailing_commas: false
