name: vegas_lit
description: This is a free to play sports simulation game

publish_to: "none"
version: 1.1.7+78

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.5.3
  cloud_firestore_web: ^2.4.3
  connectivity: ^3.0.6
  country_picker: ^2.0.8
  device_preview: ^1.0.0-alpha.10
  dio: ^4.0.0
  equatable: ^2.0.3
  firebase_analytics: ^8.3.3
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  firebase_crashlytics: ^2.2.3
  firebase_messaging: ^10.0.8
  firebase_remote_config: ^0.11.0+1
  firebase_storage: ^10.0.5
  flow_builder: ^0.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_countdown_timer: ^4.1.0
  flutter_font_icons: ^2.2.3
  flutter_svg: ^0.23.0+1
  formz: ^0.4.1
  google_fonts: ^2.1.0
  google_mobile_ads: ^0.13.5
  image_picker: ^0.8.4+3
  in_app_review: ^2.0.3
  intl: ^0.17.0
  line_awesome_flutter: ^2.0.0
  mime: ^1.0.1
  new_version: ^0.2.3
  overlay_support: ^1.2.1
  package_info_plus: ^1.3.0
  qr_code_scanner: ^0.5.2
  qr_flutter: ^4.0.0
  regexpattern: ^2.0.1
  responsive_builder: ^0.4.1
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  timezone: ^0.7.0
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  flutter_test:
    sdk: flutter
  meta: ^1.2.4
  very_good_analysis: ^2.4.0

flutter_native_splash:
  color: "#2d3540"
  image: assets/images/logo_top.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/olympics_icons/
    - assets/images/paralympics_icons/
    - assets/images/bet_game_bg/
    - assets/json/
    - assets/overlays/
    - assets/svg/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AppIcon.png"
