name: vegas_lit
description: This is a free to play sports simulation game

publish_to: "none"
version: 1.1.1+72

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  bloc: ^6.1.1
  cached_network_image: ^3.0.0
  carousel_slider: ^3.0.0
  cloud_firestore: ^1.0.7
  cloud_firestore_web: ^1.0.5
  connectivity: ^3.0.3
  country_picker: ^2.0.6
  dio: ^4.0.0
  equatable: ^2.0.0
  firebase_analytics: ^8.1.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_crashlytics: ^2.0.2
  firebase_messaging: ^10.0.4
  firebase_remote_config: ^0.10.0+3
  firebase_storage: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  flutter_countdown_timer: ^4.1.0
  flutter_icons: ^1.1.0
  flutter_svg: ^0.22.0
  formz: ^0.3.2
  google_fonts: ^2.0.0
  google_mobile_ads: ^0.13.0
  image_picker: ^0.8.0+1
  in_app_review: ^2.0.2
  intl: ^0.17.0
  line_awesome_flutter: ^1.0.1
  mime: ^1.0.0
  new_version: ^0.2.2
  overlay_support: ^1.2.1
  package_info_plus: ^1.0.0
  qr_code_scanner: ^0.5.2
  qr_flutter: ^4.0.0
  regexpattern: ^1.0.0
  responsive_builder: ^0.4.1
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  timezone: ^0.7.0
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  flutter_test:
    sdk: flutter
  meta: ^1.2.4
  very_good_analysis: ^1.0.4

flutter_native_splash:
  color: "#2d3540"
  image: assets/images/logo_top.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/olympics_icons/
    - assets/images/paralympics_icons/
    - assets/images/bet_game_bg/
    - assets/json/
    - assets/overlays/
    - assets/svg/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AppIcon.png"
