name: vegas_lit
description: This is a free to play sports simulation game

publish_to: "none"

version: 0.8.1+45

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.1.1
  bottom_sheet_bar: ^2.0.0
  carousel_slider: ^3.0.0
  circular_profile_avatar: ^2.0.0
  cloud_firestore: ^1.0.7
  cloud_firestore_web: ^1.0.5
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.0
  custom_navigation_bar: ^0.7.1
  dio: ^4.0.0
  equatable: ^2.0.0
  firebase_analytics: ^8.1.0
  firebase_core: ^1.0.2
  firebase_crashlytics: ^2.0.2
  flutter_bloc: ^6.1.1
  flutter_countdown_timer: ^4.1.0
  flutter_icons: ^1.1.0
  flutter_multi_formatter: ^1.3.6
  firebase_auth: ^1.0.1
  google_sign_in: ^4.5.9
  flutter_svg: ^0.22.0
  formz: ^0.3.2
  google_fonts: ^2.0.0
  google_mobile_ads: ^0.13.0
  instant: ^0.4.1
  intl: ^0.17.0
  jiffy: ^4.1.0
  line_awesome_flutter: ^1.0.1
  numberpicker: ^2.0.1
  package_info_plus: ^1.0.0
  path_provider: ^2.0.0
  pluto_grid: ^1.2.0
  responsive_builder: ^0.4.1
  syncfusion_flutter_datagrid: ^18.4.43-beta
  timezone: ^0.7.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.2
  uuid: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  very_good_analysis: ^1.0.4
  meta: ^1.2.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/overlays/
    - assets/svg/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AppIcon.png"
