name: vegas_lit
description: A sports betting game

publish_to: "none"

version: 0.6.6+26

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  api_client:
    path: packages/api_client
  bloc: ^6.1.1
  carousel_slider: ^3.0.0
  cloud_firestore_web: ^1.0.5
  cupertino_icons: ^1.0.0
  custom_navigation_bar: ^0.7.1
  dio: ^4.0.0
  equatable: ^2.0.0
  firebase_analytics: ^7.1.1
  firebase_core: ^1.0.2
  flutter_bloc: ^6.1.1
  flutter_icons: ^1.1.0
  flutter_multi_formatter: ^1.3.6
  formz: ^0.3.2
  google_fonts: ^2.0.0
  hive: ^2.0.2
  http: ^0.13.1
  image_picker: ^0.7.4
  instant: ^0.4.1
  line_awesome_flutter: ^1.0.1
  meta: ^1.2.4
  new_version: ^0.2.0
  numberpicker: ^2.0.1
  package_info_plus: ^1.0.0
  path_provider: ^2.0.0
  pluto_grid: ^1.2.0
  responsive_builder: ^0.4.1
  syncfusion_flutter_datagrid: ^18.4.43-beta
  timezone: ^0.7.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.2
  uuid: ^3.0.3
  very_good_analysis: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
